location /v1/ {
  proxy_pass http://api:3000/v1/;
}

location = /docs {
  proxy_pass http://api:3000/docs;
}

location /docs/ {
  proxy_pass http://api:3000/docs/;
}

location = /docs-json {
  proxy_pass http://api:3000/docs-json;
}

location /health {
  proxy_pass http://api:3000/health;
}
