def googleMirror = 'https://maven.aliyun.com/repository/google'
def offlineMavenRepo = new File(gradle.startParameter.currentDir, '../../../vendor/maven')

settingsEvaluated { settings ->
    settings.pluginManagement.repositories {
        if (offlineMavenRepo.exists()) {
            maven { url offlineMavenRepo.toURI() }
        }
        maven { url googleMirror }
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

gradle.beforeProject { project ->
    project.buildscript.repositories {
        if (offlineMavenRepo.exists()) {
            maven { url offlineMavenRepo.toURI() }
        }
        maven { url googleMirror }
        google()
        mavenCentral()
        gradlePluginPortal()
    }

    project.repositories {
        if (offlineMavenRepo.exists()) {
            maven { url offlineMavenRepo.toURI() }
        }
        maven { url googleMirror }
        google()
        mavenCentral()
    }
}
