ALTER TABLE "Order"
  ADD COLUMN "discountAmount" DECIMAL(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN "extraAmount" DECIMAL(18,2) NOT NULL DEFAULT 0;

ALTER TABLE "Invoice"
  ADD COLUMN "discountAmount" DECIMAL(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN "extraAmount" DECIMAL(18,2) NOT NULL DEFAULT 0;
